# Generated by Django 5.1.2 on 2024-10-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('TODO', 'TO DO'), ('IN_PROGRESS', 'IN PROGRESS'), ('DONE', 'DONE')], default='TODO', max_length=12),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
