# Generated by Django 5.1.2 on 2024-10-18 07:02

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_issue_status_delete_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='description',
            new_name='short_description',
        ),
        migrations.AddField(
            model_name='issue',
            name='long_description',
            field=django_ckeditor_5.fields.CKEditor5Field(default='Long Description of issue', verbose_name='Long Description'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='Medium', max_length=12),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('TODO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done')], default='TODO', max_length=12),
        ),
    ]
